#!/bin/sh

HOST=$1


PORTS="3389 22 80 445 5666 1433";

for i in $PORTS; do
	check_tcp -H $HOST -p $i >/dev/null 2>&1 && echo Port $i=yes || echo Port $i=no
done
echo -n "Checking NRPE Connectivity: "
check_nrpe -H $HOST 
