#!/bin/sh


IPS=`fping -a -g $1 2>/dev/nul`
if [ $? -gt 2 ]; then
	echo failed to run fping
	exit 1
fi


#addgroup --group misc --alias "Misc hosts"

for ip in $IPS; do
	# Check if this host already exists
	grep -qw $ip /var/log/nagios/objects.cache
	if [ $? -eq 0 ]; then
		continue
	fi
	RES=`host $ip`
	if [ $? -gt 0 ]; then
		HOSTN=$ip
	else
		HOSTN=`echo $RES | head -n 1 | sed 's/.*name pointer //' | sed 's/\.$//'`
	fi
	echo $ip = $HOSTN
	addhost --host $HOSTN --ip $ip --group misc --templates autodiscover
done

