#!/bin/sh
#
# Copyright 2010, Pall Sigurdsson <palli@opensource.is>
#
# This script is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# About this script
# 
# This process checks if HP Dataprotector is up and running with the
# omnisv command. Issues a warning if not all services are up

/opt/omni/sbin/omnisv -status | grep "Status: All Data Protector relevant processes/services up and running."

RESULT=$?

if [ $RESULT -gt 0 ]; then
	echo "Critical, some Data Protector services are in stopped state"
	exit 1	
fi


